feat: add maps
emiliosheinz/sos-pet pull request #49
Opened 2024-05-15 23:57 UTC by RigottiG

- Add latitude and longitude by Google Maps API
- Add a Map

![image](https://github.com/emiliosheinz/sos-pet/assets/13246770/6528613a-f544-4a58-a60b-9146b0f897b9)

2024-05-16 00:38 UTC, emiliosheinz requested changes

2024-05-16 00:38 UTC, emiliosheinz commented on package.json
> +    "redaxios": "^0.5.1",
Porque não o axios?

2024-05-16 00:38 UTC, emiliosheinz commented on prisma/schema.prisma
> +  longitude Float?
Qual a estratégia para popular esses campos em abrigos já criados?

2024-05-16 00:38 UTC, emiliosheinz commented on src/app/page.tsx
> +import "leaflet-defaulticon-compatibility";
Consegue colocar esses imports la no topo?

2024-05-16 00:38 UTC, emiliosheinz commented on src/app/page.tsx
> +}
Porque isso tem que ser um componente? Não pode simplesmente ser um hook ja que sempre retorna null?

2024-05-16 00:38 UTC, emiliosheinz commented on src/app/page.tsx
> +  ]); // Default to Porto Alegre
Acho que podia salvar `[-30.0346, -51.2177]` em uma const, evita a necessidade de comentários.

```ts
const POA_LAT_LNG_TUPLE: LatLngTuple = [-30.0346, -51.2177]
```

2024-05-16 00:38 UTC, emiliosheinz commented on src/app/shelter/page.tsx
> +    };
O que acha de ao menos abstrair em uma lib da vida pra não fica uma chamada API avulsa assim?

`src/libs/google-maps.ts`

```
export const googleMaps = {
  ...
}
```

2024-05-16 00:38 UTC, emiliosheinz commented on src/schemas/shelter.ts
> +    longitude: z.number().optional(),
Acho que isso aqui é um problema. Até então o shelter era uma coisa só da api ao form, porém agora o form não tem o esses dois campos novos, isso é um campo extra que é passado depois que ele foi submetido. Se tu olhar em `async function onSubmit(values: z.infer<typeof shelterSchema>) {` tu vai ver que o `values` tá tipado de tal forma que da a enteder que pode vir latitude e longitude nele, mas nunca vai vir. 

Eu diria pra criar duas coisas separadas, `formShelterSchema` e `apiShelterSchema`. Que compartilham 90% dos campos mas diferem na latitude e longitude. O que tu acha?

2024-05-16 00:38 UTC, emiliosheinz commented on src/app/page.tsx
> +      </MapContainer>
Não sei se é o lugar ideal mostrar isso no topo de tudo na Home.

@willMoraes e @pinheiroduda o que vocês acham? 

Me parece mais apropriado criar uma rota `/map` da vida onde vamos só renderizar o mapa.

2024-05-16 00:40 UTC, RigottiG commented on package.json
> +    "redaxios": "^0.5.1",
Não precisamos de tudo que o axios tem, e o redaxios só traz a API com menos 1Kb (~800b)

2024-05-16 00:41 UTC, RigottiG commented on prisma/schema.prisma
> +  longitude Float?
Precisa ser manualmente nos 4 já criados.

2024-05-16 00:41 UTC, RigottiG commented on src/app/page.tsx
> +}
Peguei assim da documentação, mas agora vendo a solução pra funcionar no Next, vou precisar mandar tudo isso pra dentro de outro componente e chamar na home 😢

2024-05-16 00:43 UTC, RigottiG commented on src/app/page.tsx
> +      </MapContainer>
E como ficaria o acesso para essa página ? eu acabei seguindo aquele outro site onde o mapa fica no topo

2024-05-16 00:44 UTC, emiliosheinz commented on prisma/schema.prisma
> +  longitude Float?
Não tem como automatizar isso de alguma forma?

2024-05-16 13:34 UTC, emiliosheinz commented on src/app/page.tsx
> +      </MapContainer>
No header pode ter um item "Mapa"

2024-05-16 15:38 UTC, RigottiG commented on prisma/schema.prisma
> +  longitude Float?
Não, pois precisaria abrir cada abrigo e salvar, a chamada ia ocorrer e atualizar, porém não temos como editar os abrigos de outros HOJE via sistema, somente banco.

2024-05-16 21:47 UTC, emiliosheinz commented on prisma/schema.prisma
> +  longitude Float?
Mas é exatamente isso que eu quero dizer, automatizar um script que faça a chamada pra API e execute o comando SQL pra atualizar esses campos.

2024-05-16 22:25 UTC, willMoraes commented on src/app/page.tsx
> +      </MapContainer>
Achei que ficou muito grande pra ser na home também. Gosto de ter uma rota pra isso. 

Acho que podemos ter um link no header. 

Acho que uma ideia bem legal, seria ter um ícone de mapa no card, onde clicando nele, vamos pra página de Mapa com o item no centro. Daria pra passar lat, long por queryParams pra esse /map

2024-05-16 22:52 UTC, RigottiG commented on prisma/schema.prisma
> +  longitude Float?
O tempo pra criar um script pra fazer a chamada é o muito maior que rodar 4 vezes a api manualmente e pegar os dados e colocar em um mesmo insert, tá over demais

2024-05-18 14:03 UTC, emiliosheinz requested changes

2024-05-18 14:03 UTC, emiliosheinz commented on src/schemas/api.ts
> +});
O nome disso aqui não está adequado. Acredito que isso poss ficar dentro do arquivo `schemas/shelter` com o nome de `apiShelterSchema` ou algo semelhante. `apiSchema` é muito genérico e só funciona porque temos uma única entidade na aplicação. A partir do momento que passarmos a ter lares temporários também isso aqui vai ter que ser refatorado.

2024-05-18 14:15 UTC, emiliosheinz commented
Testei local, e achei muito bom 🚀

2024-05-18 14:16 UTC, emiliosheinz commented on src/app/shelter/page.tsx
> +      console.error("Error fetching coordinates or submitting shelter:", error);
Outro ponto com relação a essas modificações é que o estado de loading no botão não vai ser corretamente refletido visto que a chamada pra API do google não modifica nenhum estado.

2024-05-20 22:09 UTC, emiliosheinz approved these changes
LGTM!

2024-05-20 22:32 UTC, emiliosheinz requested changes

2024-05-20 22:32 UTC, emiliosheinz commented on src/components/header/index.tsx
> +            </li>
Depois do merge do meu PR isso aqui tem que ser mudado pra seguir o padrão dos outros links.

2024-05-20 22:32 UTC, emiliosheinz commented on src/components/header/sidebar/index.tsx
> +              </li>
Mesma coisa

2024-05-21 00:07 UTC, emiliosheinz approved these changes

2024-05-21 13:04 UTC, merged