feat: enable create shelters
emiliosheinz/sos-pet pull request #53
Opened 2024-05-16 23:25 UTC by willMoraes

- Enable user create more than one shelter
- Enable user to delete shelter by Id
- Create User Shelters page
- Create Edit Shelter page
- Crete delete shelter dialog

![image](https://github.com/emiliosheinz/sos-pet/assets/8379513/6858a347-4f2e-484e-a7bf-cb6b4200b9c6)

2024-05-18 14:37 UTC, emiliosheinz commented
Revisei a questão da estrutura de rotas como tu pediu e acho que da pra melhorar um pouco principalmente pra facilitar a questão de controle de autenticação depois.

Acredito que tudo que é coisa referente ao usuário em si pode ficar dentro de `/user` dessa forma conseguimos colocar um auth guard nessa camada. 

Ficaria algo como:

```
src
  app
    about
    api
    privacy-policy
    signin
    terms-of-use
    shelters (seria para uma possivel listagem public)
    user (tudo que é referente a um user)
      shelters (listagem de shelter do usuário)
        create (criação de um shelter para o usuário)
        [id]/edit (edição de shelter do usuário)
```

O que tu acha?

2024-05-29 00:24 UTC, emiliosheinz requested changes

2024-05-29 00:24 UTC, emiliosheinz commented on src/app/user/shelters/layout.tsx
A lógica deste arquivo foi replica outras 2 vezes: (1) `src/app/user/shelters/[id]/edit/layout.tsx` e (2)`src/app/user/shelters/create/layout.tsx`. De acordo com a [documentação do Next](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts) layouts são compartilhados entre diferentes rotas, ou seja, como a edição e a criação de shelters são rotas que estão abaixo desta, elas também renderizam este `layout` aqui e isso faz com que duas requests (uma delas desnecessária) sejam feitas para o endpoint de session.

Aconselho apagar os outros dois layouts mencionados acima e deixar apenas esse aqui. Na pratica o resultado é o mesmo porém com uma única request.

2024-05-29 00:24 UTC, emiliosheinz commented on src/app/user/shelters/layout.tsx
> +    redirect("/signin?callbackUrl=/user/shelters/create");
O único galho é que vamos ter que aqui vamos ter que ver se existe uma forma de atribuir o `callBackUrl` de acordo com a rota destino que a pessoa está acessando (listagem, criação ou edição de shelters).

2024-05-29 00:24 UTC, emiliosheinz commented on src/app/user/shelters/page.tsx
> +    if (!items || items.length === 0) {
```suggestion
    if (!items?.length) {
```

2024-05-29 00:24 UTC, emiliosheinz commented on src/app/user/shelters/page.tsx
> +function Shelters({ items }: { items?: ShelterTable[] | null }) {
Items tem que ser mesmo optional e `null`? Não pode ser um ou outro? Qual a diferença caso seja `undefined` e caso seja `null`?

2024-05-29 00:24 UTC, emiliosheinz commented on src/components/shelter/form-edit-register/dialog-delete/index.tsx
Essa organização de componentes está confusa, porque esses aqui tu colocou dentro do `src/components` e os outros tu deixou dentro do `src/app`? Caso esses componentes sejam referentes ao um grupo de funcionalidades específico diria pra deixar dentro do `src/app` junto da funcionalidade em si. Caso eles sejam globais, utilizados em vários lugares da aplicação, deixa aqui (mas ai eles tem que ser genéricos o suficiente, o que não me parece o caso).

2024-05-29 00:24 UTC, emiliosheinz commented on src/components/shelter/form-edit-register/index.tsx
> +              {isEditing && shelter.id && (
Acredito que tu está tendo que validar o id aqui porque a tipagem de shelter não está 100% correta.

2024-05-29 00:24 UTC, emiliosheinz commented on src/schemas/shelter.ts
> +  id: z.number().optional(),
Ehhh, isso aqui com certeza vai gerar dor de cabeça e validações desnecessárias la na frente. Idealmente deveríamos ter schemas separados e não tentar colocar tudo em um único lugar. O que quero dizer é que o type para criar um shelter e o type que representa o que é retornado no endpoint que busca os shelters, difere. Um tem id e outro não. Da forma que está ambos podem opcionalmente ter id. O que não é verdade.

2024-05-29 00:24 UTC, emiliosheinz commented on src/server/api/routers/shelter.ts
> +  findById: publicProcedure.input(InputIdParams).query(async (opts) => {
Segue o padrão de desestruturar direto o input aqui ao invés de criar esse opts.

2024-05-29 00:24 UTC, emiliosheinz commented on src/server/api/routers/shelter.ts
> +        id: result.id,
Percebe que id não é opcional?

2024-05-29 00:24 UTC, emiliosheinz commented on src/server/api/routers/shelter.ts
> +  findUserShelterById: protectedProcedure
Essa procedure não deveria estar dentro do `user/shelters` que foi criado? O mesmo vale para o update e o delete.

2024-05-29 00:25 UTC, emiliosheinz commented on src/app/user/shelters/create/page.tsx
> +export default function ShelterPage() {
Tem que dar uma revisada no nome das pages e dos layouts, não tão 100%.

2024-05-29 00:30 UTC, emiliosheinz commented
Só deixando esse comentário pra lembrar que tem a questão do UUID pra ser vista ainda. Correto?

2024-05-29 23:06 UTC, willMoraes commented on src/app/user/shelters/[id]/edit/page.tsx
> +}
Não muito o que fazer. 

O que fiz foi separar a de 404 de demais erros, onde mostro um toast.

2024-05-29 23:20 UTC, willMoraes commented on src/app/user/shelters/data-table.tsx
> +  );
Eu quero refatorar isso, por enquanto essa tabela é só um quebra galho. Não gostei dessa listagem ser em tabela, quero fazer uns cards mais bonitinhos.

2024-05-29 23:22 UTC, willMoraes commented on src/app/user/shelters/layout.tsx
Boa, não lembrava disso. Removido

2024-05-29 23:23 UTC, willMoraes commented on src/app/user/shelters/layout.tsx
> +    redirect("/signin?callbackUrl=/user/shelters/create");
Por enquanto pra não complicar, acho que podemos mandar tudo pra `users/shelter`

2024-05-29 23:31 UTC, willMoraes commented on src/app/user/shelters/page.tsx
> +function Shelters({ items }: { items?: ShelterTable[] | null }) {
da pra manter só o `undefined`

2024-05-30 00:24 UTC, willMoraes commented on src/app/user/shelters/columns.tsx
> +    accessorKey: "Vagas",
Por estar em português? Ajustado

2024-06-01 20:32 UTC, emiliosheinz requested changes

2024-06-01 20:32 UTC, emiliosheinz commented on src/app/user/shelters/[id]/edit/page.tsx
> +  }
Isso aqui é má pratica pois o toast vai ser disparado a cara rerender do componente. Acredito que o useQuery deva ter parâmetros semelhantes a mutation para executar uma callback quando ocorre erro ou sucesso ou até mesmo, quando a request é finalizada.  Ou então tu pode renderizar algo na tela mesmo com um alert dizendo que deu ruim buscando os dados.

2024-06-03 22:46 UTC, willMoraes commented on src/app/user/shelters/[id]/edit/page.tsx
> +  }
Ajustado. Gostei da ideia do alert. 

pela doc do useQuery, o correto seria utilizar o objeto erro disponibilizado pela query mesmo. Mas resolvi remover o toast, já que vamos ter o alert.

![image](https://github.com/emiliosheinz/sos-pet/assets/8379513/b1edb6f3-75a6-4e4f-aaab-0ec1581c60a1)

2024-06-04 00:05 UTC, emiliosheinz approved these changes

2024-06-04 00:05 UTC, merged